apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: projet-infonuagique
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30012