apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  labels:
    app: postgres
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );

    INSERT INTO users (name) VALUES 
      ('Marie'), 
      ('Kamil'), 
      ('Abdourahmane');
