{
 "title": "Minikube Monitoring",
 "time": { "from": "2025-04-18T18:33:12.090Z", "to": "2025-04-18T21:24:18.890Z" },
 "panels": [
  {
   "title": "Gestion des ressources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilisé",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{pod=~\"backend-.*\"}[1m]) * 100\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mémoire utilisée (Mo)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{pod=~\"backend-.*\"} / 1024 / 1024\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Test de Performance (traitement des requêtes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Requêtes HTTP/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"backend\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence moyenne HTTP (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 2 },
   "targets": [
    {
     "expr": "(http_request_duration_seconds_sum{job=\"backend\"} / http_request_duration_seconds_count{job=\"backend\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 2 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"backend\"}[1m])) by (le)) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% de réponses 5xx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"5..\", job=\"backend\"}) / sum by(handler) (http_requests_total{job=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Test de Résilience", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Redémarrages de pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 1, "y": 10 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"backend-.*\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilité du Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "up{job=\"backend\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test de Scalabilité",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nombre de pods actifs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(kube_pod_info{pod=~\"backend-.*\"})\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}